/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    CodeMirrorMark: typeof import('./components/CodeMirrorMark.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    PageTem: typeof import('./components/PageTem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestPage: typeof import('./components/TestPage.vue')['default']
  }
}
