/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/json5': RouteRecordInfo<'/json5', '/json5', Record<never, never>, Record<never, never>>,
    '/jsonDiff': RouteRecordInfo<'/jsonDiff', '/jsonDiff', Record<never, never>, Record<never, never>>,
    '/jsonF': RouteRecordInfo<'/jsonF', '/jsonF', Record<never, never>, Record<never, never>>,
    '/qqInvoice': RouteRecordInfo<'/qqInvoice', '/qqInvoice', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/txt2sql': RouteRecordInfo<'/txt2sql', '/txt2sql', Record<never, never>, Record<never, never>>,
    '/updateColSql': RouteRecordInfo<'/updateColSql', '/updateColSql', Record<never, never>, Record<never, never>>,
    '/visio2': RouteRecordInfo<'/visio2', '/visio2', Record<never, never>, Record<never, never>>,
  }
}
